//! Structural Verilog of the sized top module, kept PD-clean: only port and
//! `wire` declarations and cell instances with named connections: no
//! `assign`, no behavioural code, no escaped identifiers. Each port's net
//! takes the port's name, so a net shared by two ports (which would need an
//! `assign`) is rejected.
//!
//! Cell masters are named as in the SPICE deck. [`render_cells`] gives
//! their black-box declarations for tools that need every module defined.

use crate::backend::{cell_master, net_name, sanitize};
use crate::ir::{Direction, IrError, Module, PinOwner};
use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;

/// The top module netlist.
pub fn render(m: &Module) -> Result<String, IrError> {
    for (_, net) in m.nets().iter() {
        let ports: Vec<&str> = net
            .pins
            .iter()
            .filter_map(|&p| match m.pins()[p].owner {
                PinOwner::Port(id) => Some(m.ports()[id].name.as_str()),
                PinOwner::Cell(_) => None,
            })
            .collect();
        if ports.len() > 1 {
            return Err(IrError::Unsupported(format!(
                "ports {} of '{}' share one net, which needs an assign; buffer them first",
                ports.join(", "),
                m.name
            )));
        }
    }

    let top = sanitize(&m.name);
    let ports: Vec<(String, Direction)> = m.ports().iter().map(|(_, p)| (sanitize(&p.name), p.dir)).collect();
    let port_names: BTreeSet<&str> = ports.iter().map(|(n, _)| n.as_str()).collect();

    let mut out = String::new();
    writeln!(out, "// {top}: logical-effort sized structural netlist").unwrap();
    writeln!(out, "// generated by {} on {}", crate::build_info::generator(), crate::build_info::now_utc()).unwrap();
    for (k, v) in m.attrs.iter().filter(|(k, _)| k.starts_with("macro_gen.inverted.")) {
        writeln!(out, "// {k} = {v}").unwrap();
    }
    let names: Vec<&str> = ports.iter().map(|(n, _)| n.as_str()).collect();
    writeln!(out, "module {top} ({});", names.join(", ")).unwrap();
    for (name, dir) in &ports {
        let kw = if *dir == Direction::Input { "input" } else { "output" };
        writeln!(out, "  {kw} {name};").unwrap();
    }

    let wires: BTreeSet<String> = m
        .nets()
        .ids()
        .into_iter()
        .map(|n| net_name(m, Some(n)))
        .filter(|n| !port_names.contains(n.as_str()))
        .collect();
    // Instances, wires and ports share one Verilog scope.
    for (_, cell) in m.cells().iter() {
        let inst = sanitize(&cell.name);
        if wires.contains(&inst) || port_names.contains(inst.as_str()) {
            return Err(IrError::Unsupported(format!(
                "instance '{inst}' in '{}' has the same name as a net", m.name
            )));
        }
    }
    for w in &wires {
        writeln!(out, "  wire {w};").unwrap();
    }
    out.push('\n');

    for (id, cell) in m.cells().iter() {
        let (master, _, _) = cell_master(m, id)?;
        let conns: Vec<String> = cell
            .pins
            .iter()
            .map(|&p| format!(".{}({})", m.pins()[p].name, net_name(m, m.pins()[p].net)))
            .collect();
        writeln!(out, "  {master} {} ({});", sanitize(&cell.name), conns.join(", ")).unwrap();
    }
    writeln!(out, "endmodule").unwrap();
    Ok(out)
}

/// Black-box declarations (ports only) of every cell master `m` uses.
pub fn render_cells(m: &Module) -> Result<String, IrError> {
    let mut masters: BTreeMap<String, usize> = BTreeMap::new();
    for (id, _) in m.cells().iter() {
        let (master, stage, _) = cell_master(m, id)?;
        masters.insert(master, stage.n_inputs);
    }
    let mut out = format!(
        "// Cell masters (black boxes); transistor-level views are in the SPICE deck.\n// generated by {}\n",
        crate::build_info::generator()
    );
    for (master, n) in masters {
        let ins: Vec<String> = (0..n).map(crate::ir::GateType::input_pin_name).collect();
        writeln!(out, "\n(* blackbox *)\nmodule {master} ({}, y);", ins.join(", ")).unwrap();
        for i in &ins {
            writeln!(out, "  input {i};").unwrap();
        }
        writeln!(out, "  output y;\nendmodule").unwrap();
    }
    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ir::GateType;
    use crate::passes::Pass;
    use crate::passes::cmos_map::CmosMap;
    use crate::passes::cmos_map::tests::module;
    use crate::passes::sizing::{LogicalEffortSizing, SizingParams};

    #[test]
    fn comb_chain_netlist_is_structural() {
        let mut d = module(
            &[("a", Direction::Input), ("b", Direction::Input), ("c", Direction::Input), ("y", Direction::Output)],
            &[("u0", GateType::And2, &["a", "b"], "ab"), ("u1", GateType::Nor2, &["ab", "c"], "y")],
            false,
        );
        CmosMap.run(&mut d).unwrap();
        LogicalEffortSizing(SizingParams { gamma: 2.0, cload: 16.0, cin_max: 1.0 }).run(&mut d).unwrap();
        let v = render(d.module(d.top().unwrap())).unwrap();
        assert!(!v.contains("assign"));
        assert!(v.starts_with("// top:"));
        assert!(v.contains("module top (a, b, c, y);\n  input a;"));
        assert!(v.contains("  wire ab;\n  wire u0_n;\n"));
        assert!(v.contains(" u0 (.in0(a), .in1(b), .y(u0_n));"));
        assert!(v.contains(" u1 (.in0(ab), .in1(c), .y(y));"));
        assert!(v.trim_end().ends_with("endmodule"));

        let cells = render_cells(d.module(d.top().unwrap())).unwrap();
        assert_eq!(cells.matches("(* blackbox *)").count(), 3);
    }
}
