# sky130_adapter.toml
[environment]
vdd = 1.8
min_length = 0.15 # in microns
include_path = "/home/joyenbenitto/pdk/open_pdks/sources/sky130_fd_pr/combined_models/sky130.lib.spice"
corner = "tt"

[models]
nmos = "sky130_fd_pr__nfet_01v8"
pmos = "sky130_fd_pr__pfet_01v8"

[syntax]
device_template = "M{{name}} {{d}} {{g}} {{s}} {{b}} {{model}} w={{w}} l={{l}}"