# sky130_adapter.toml
[environment]
vdd = 1.8
min_length = 0.15 # in microns
include_path = "/usr/share/pdk/sky130A/libs.tech/ngspice/sky130.lib.spice"
corner = "tt"

[models]
nmos = "sky130_fd_pr__nfet_01v8"
pmos = "sky130_fd_pr__pfet_01v8"

[syntax]
# The templated instantiation string. 
# Rust calculates W and L, then injects them here.
device_template = "M{{name}} {{d}} {{g}} {{s}} {{b}} {{model}} w={{w}} l={{l}}"